### ISSUE TITLE
neo4j_import

### ISSUE THREAD

**Issue by Btibert3** [keithmcnulty/neo4jshell#2]
`neo4j_import` also fails with local dev.  While clearly articulated in the updated README, I wonder if local dev could be supported with a flag remote=TRUE|FALSE where if TRUE, perform as currently coded, if FALSE, just work with local dev paths.

```
options(stringsAsFactors=FALSE)

## load the packages
library(neo4jshell)

## graph setup
graph = list(address = "bolt://localhost:7687", uid = "neo4j", pwd = "password")
SHELL_LOC = "/Users/btibert/neo4j-community-3.5.8/bin/cypher-shell"
IMPORT_LOC = "/Users/btibert/neo4j-community-3.5.8/import/"

## wakefield - generate a simple dataset
install.packages("wakefield")
library(wakefield)
df = r_data_frame(100, 
                  id, 
                  age,
                  gender)
readr::write_csv(df, "test-df.csv")
# > list.files(pattern = "test")
# [1] "test-df.csv"
neo4j_import(graph, source="test-df.csv", import_dir = IMPORT_LOC)
```

**Comment by keithmcnulty** [comment]
Thanks - that's a good thought - and likely not very difficult.  Let me look into that asap.

**Comment by Btibert3** [comment]
I threw in a PR for you to check out

**Comment by keithmcnulty** [comment]
I actually was writing up the adjustments and pushed them to master - for all the three server management functions to work locally.  Try reinstalling and giving it a go and if there are bugs I can look at your PR.  (Would still need to update README if this works, would would be great if you could contribute a working local dev example for the README?

**Comment by Btibert3** [comment]
Tested with this code:


```
options(stringsAsFactors=FALSE)

## load the packages
library(neo4jshell)

## graph setup
graph = list(address = "bolt://localhost:7687", uid = "neo4j", pwd = "password")
SHELL_LOC = "/Users/btibert/neo4j-community-3.5.8/bin/cypher-shell"
IMPORT_LOC = "/Users/btibert/neo4j-community-3.5.8/import/"

## wakefield - generate a simple dataset
# install.packages("wakefield")
library(wakefield)
df = r_data_frame(100, 
                  id, 
                  age,
                  gender)
readr::write_csv(df, "test-df.csv")
# > list.files(pattern = "test")
# [1] "test-df.csv"
neo4j_import(local = TRUE, graph, source="test-df.csv", import_dir = IMPORT_LOC)


## remove the file
neo4j_rmfiles(local = TRUE, graph, files="test-df.csv", import_dir = IMPORT_LOC)

## create a test subdirectory
fs::dir_create(paste0(IMPORT_LOC, "test-dr"))
fs::dir_ls(IMPORT_LOC)
neo4j_rmdir(local = TRUE, graph, dir = "test-dr", import_dir = IMPORT_LOC)
fs::dir_ls(IMPORT_LOC)

```

Works for me.  Closing this PR and will make another for the README.  Please us those of us watching the project how you want additional PR's to occur.  Is the preference for an Issue to track Feature Requests or just submit the PR.  If you check my repos, I have been dabbling here and there with just personal projects around R and Neo4j, but one use-case I see is around additional server management utilities. 

Great stuff.  Excited to see where this goes.
