### ISSUE TITLE
Contributions Note

### ISSUE THREAD

**Issue by Btibert3** [keithmcnulty/neo4jshell#6]
Just making it more formal as I am really excited for this project.  How do you want end users contributing to the project?

**Comment by keithmcnulty** [comment]
1.  Test and raise issues discovered with the existing codebase.  Would like to submit to CRAN at a point where it has been sufficiently tested.  Particularly keen to ensure it works well on Ubuntu and in Windows.

2.  Suggest new functionality - there are possibly further useful server management utilities to be written.  

3.  Happy to receive PRs, but better to assign dev once the issues or new functionality have been identified and agreed.
