### ISSUE TITLE
Server Management

### ISSUE THREAD

**Issue by Btibert3** [keithmcnulty/neo4jshell#7]
As a user who may develop locally for prototyping, or on a remote server, I need the ability to start/stop/restart the `neo4j` server.  I would expect to run a simple function such as `neo4j_start` or `neo4j_stop` to perform the operation.  

Moreover, I expect the function to understand the state of the server.  For example, if neo4j is running and I attempt to call `neo4j_start`, the function would return a message telling me that the server is already run and no action was taken.

##  Notes

- It's probably junk now, but I had this working for older versions and my needs locally [here](https://github.com/Btibert3/neoimportR/tree/master/R)
- I also had a utility to wipe the database, which is helpful for local prototyping and building of a data model. A similar utility was also included in `RNeo4j`.

**Comment by keithmcnulty** [comment]
How about a function which start/stopped the server, or returned the precise text of any errors encountered in doing so?   By using `sys::exec_wait()` that is very feasible.

In you experience is there a substantial difference in command between localhost and a remote server?  Would be great to see some command line examples.

Thanks so much for the suggestion.

**Comment by Btibert3** [comment]
Sure, whatever you think is best.  My view is that this can be the `go-to` for neo4j and R, and as someone with far too many 80% finished blog posts, my biggest struggle is that I want to show how easy it is to use both, and managing the server is the hardest part.  A simplified API via an R package would go a long way to make that much easier.  Doesn't have to boil the ocean, but basic management and use for in/out ETL would be massive.  

My prior approach for all 4 functions (start/stop/restart/wipe) via the command line as you do, but your code is much more elegant.  My reason for these was that it allows me to properly manage a local server which can help automate things.  That said, I understand that the view would be that you log into a server, my view I suppose is that I am already _on_ the server.

Thanks for quick work on this package!

**Comment by keithmcnulty** [comment]
I have added five functions `neo4j_start()`, `neo4j_stop()`, `neo4j_restart()`, `neo4j_status()` and `neo4j_wipe()`.  I have also added intelligent sensing of local operating systems, as the existing code would only have worked in Unix-based platforms.  Can you double check that everything works on your system, and I will get someone to test it on a windows system.

**Comment by Btibert3** [comment]
This is fantastic.  I just ran through a quick test (I am on a Mac)  with the code below; worked like a dream.

```
options(stringsAsFactors = FALSE)

graph = list(address = "bolt://localhost:7687", uid = "neo4j", pwd = "password")
SHELL_LOC = path.expand("~/neo4j-community-3.5.8/bin/cypher-shell")
IMPORT_LOC = path.expand("~/neo4j-community-3.5.8/import/")
SERVER_LOC = path.expand("~/neo4j-community-3.5.8/bin/neo4j")
DB_LOC = path.expand("~/neo4j-community-3.5.8/data/")

library(neo4jshell)
neo4j_status(neo4j_path = SERVER_LOC)
neo4j_stop(SERVER_LOC)
neo4j_start(SERVER_LOC)
neo4j_query(graph, qry="MATCH (n) RETURN count(n) as total", shell_path = SHELL_LOC)
neo4j_stop(SERVER_LOC)
neo4j_wipe(graph = "graph.db", data_path = DB_LOC)
neo4j_start(SERVER_LOC)
neo4j_query(graph, qry="MATCH (n) RETURN count(n) as total", shell_path = SHELL_LOC)

```

**Comment by Btibert3** [comment]
Considering this closed, and added to the README in the PR noted above to expand the help and example code on these new features
